"""Diff store, ported from the monolith's ``src/api/routes/diff.py`` — an
in-memory ``OrderedDict`` LRU (50 entries) in front of a write-through
on-disk cache under the app's own data dir.

The monolith's original was memory-only, on the theory that diffs are
throwaway viewer artifacts. That held right up until the SPA learned to
restore its open windows across a reload (aw-workspace-ui's
``apps/appWindowKeys.js``): a restored diff window whose id died with the
last workspace restart renders the "not found or expired" page, which reads
as a broken window rather than an expired artifact. Cheap to fix — a diff is
a self-contained blob of HTML — so they now survive a restart.

Storage is ``<AW_WORKSPACE_HOME>/data/diff-tool/diffs/<id>.json``, the
durable per-app tree ``fs:workspace-data`` names (see aw-workspace's
``src/apps/runtime.py`` on ``$AW_APP_DATA``: package-relative state looks
persistent but is deleted wholesale on uninstall/update). Still NOT a DB:
these are cache entries with a retention cap, not records.

WebSocket broadcast follows the same ``activate()``-sets-the-loop-directly
pattern as aw-app-presentations' ``storage.py``: F1 hot-loads this app's
sub-app via a bare ``Mount()`` into the already-running process, so
Starlette's ``@api.on_event("startup")`` never fires for it — the loop must
be handed to ``set_loop()`` from ``plugin.py``'s ``activate(ctx)`` instead,
which runs inside the real running event loop.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import uuid
from collections import OrderedDict
from pathlib import Path

logger = logging.getLogger("diff_app.storage")

APP_ID = "diff-tool"
_MAX_DIFFS = 50
# Disk holds more than memory: the whole point is surviving a restart, and a
# diff the user still has open in a restored window may be well past the 50
# most recent. Bounded all the same — this is a cache, not an archive.
_MAX_DIFFS_ON_DISK = 200
DEFAULT_WORKSPACE_CONTAINER_DIR = "/opt/aw-workspace"


def default_data_dir() -> str:
    """``<AW_WORKSPACE_HOME>/data/diff-tool`` — the same layout every other
    app's data dir uses, and what the runtime binds for ``fs:workspace-data``.

    The fallback resolves against ``AW_WORKSPACE_CONTAINER_DIR`` rather than
    ``~``: the home dir differs between the workspace process and a spawned
    agent-runner sharing the same mount, and only the container dir is stable
    across both.
    """
    home = os.environ.get("AW_WORKSPACE_HOME") or os.path.join(
        os.environ.get("AW_WORKSPACE_CONTAINER_DIR", DEFAULT_WORKSPACE_CONTAINER_DIR),
        ".aw-workspace",
    )
    return os.path.join(home, "data", APP_ID)


class DiffStore:
    def __init__(self, data_dir: str | None = None):
        self._store: "OrderedDict[str, dict]" = OrderedDict()
        self._listeners: set = set()
        self._loop: asyncio.AbstractEventLoop | None = None
        # None disables persistence entirely (a test double, or an activate()
        # whose ctx lacks the capability) — the store still works, it just
        # goes back to being memory-only.
        self._dir: Path | None = Path(data_dir) / "diffs" if data_dir else None

    def set_loop(self, loop: asyncio.AbstractEventLoop):
        self._loop = loop

    def create(self, title: str, html: str, diff_id: str | None = None) -> dict:
        diff_id = diff_id or uuid.uuid4().hex[:12]
        entry = {"id": diff_id, "title": title, "html": html}
        self._store[diff_id] = entry
        self._store.move_to_end(diff_id)
        if len(self._store) > _MAX_DIFFS:
            self._store.popitem(last=False)
        self._write(entry)
        logger.info("diff created: %s (%s)", diff_id, title)
        self._broadcast({"type": "diff_open", "diff": {"id": diff_id, "title": title}})
        return entry

    def get(self, diff_id: str) -> dict | None:
        entry = self._store.get(diff_id)
        if entry is not None:
            self._store.move_to_end(diff_id)
            return entry
        # Missing from memory means evicted by the LRU or lost to a restart —
        # either way disk is the fallback, and a hit is promoted so a window
        # being read repeatedly doesn't hit the filesystem every time.
        entry = self._read(diff_id)
        if entry is not None:
            self._store[diff_id] = entry
            self._store.move_to_end(diff_id)
            if len(self._store) > _MAX_DIFFS:
                self._store.popitem(last=False)
        return entry

    # ------------------------------------------------------------------
    # Disk cache
    # ------------------------------------------------------------------
    # Every path here is best-effort: a full disk or a read-only mount must
    # degrade this app to its old memory-only behaviour, never fail a diff the
    # caller is waiting on.

    def _path(self, diff_id: str) -> Path | None:
        # Ids are generated by uuid4().hex here, but `diff_id` is also accepted
        # straight off the wire by POST /diffs — so reject anything that isn't
        # a bare token before it becomes a path and escapes the data dir.
        if self._dir is None or not diff_id or not diff_id.replace("-", "").replace("_", "").isalnum():
            return None
        return self._dir / f"{diff_id}.json"

    def _write(self, entry: dict) -> None:
        path = self._path(entry["id"])
        if path is None:
            return
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write-then-rename: a reader must never observe a half-written
            # file, and a diff's HTML is large enough for that to be real.
            tmp = path.with_suffix(".json.tmp")
            tmp.write_text(json.dumps(entry), encoding="utf-8")
            tmp.replace(path)
            self._prune()
        except OSError as exc:
            logger.warning("diff %s not persisted: %s", entry["id"], exc)

    def _read(self, diff_id: str) -> dict | None:
        path = self._path(diff_id)
        if path is None or not path.is_file():
            return None
        try:
            entry = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            logger.warning("diff %s unreadable, dropping: %s", diff_id, exc)
            try:
                path.unlink()
            except OSError:
                pass
            return None
        return entry if isinstance(entry, dict) and entry.get("id") == diff_id else None

    def _prune(self) -> None:
        if self._dir is None:
            return
        try:
            files = sorted(self._dir.glob("*.json"), key=lambda p: p.stat().st_mtime)
        except OSError:
            return
        for stale in files[:-_MAX_DIFFS_ON_DISK] if len(files) > _MAX_DIFFS_ON_DISK else []:
            try:
                stale.unlink()
            except OSError:
                pass

    # ------------------------------------------------------------------
    # WebSocket broadcast
    # ------------------------------------------------------------------

    def add_listener(self, ws):
        self._listeners.add(ws)

    def remove_listener(self, ws):
        self._listeners.discard(ws)

    def _broadcast(self, msg: dict):
        if not self._listeners or not self._loop:
            return
        data = json.dumps(msg)
        self._loop.call_soon_threadsafe(asyncio.ensure_future, self._send_all(data))

    async def _send_all(self, data: str):
        dead = set()
        for ws in self._listeners:
            try:
                await ws.send_text(data)
            except Exception:
                dead.add(ws)
        for ws in dead:
            self._listeners.discard(ws)
